<a href="https://colab.research.google.com/github/malavikasreekumar/Titanic/blob/master/Titanic1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [2]:
cd gdrive

/content/gdrive


In [3]:
cd My Drive

/content/gdrive/My Drive


In [0]:
#import libraries and dataset
import numpy as np
import pandas as pd
dataset=pd.read_csv('Titanic.csv')

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  1309 non-null   int64  
 1   Pclass       1309 non-null   int64  
 2   Sex          1309 non-null   object 
 3   Age          1046 non-null   float64
 4   SibSp        1309 non-null   int64  
 5   Parch        1309 non-null   int64  
 6   Fare         1308 non-null   float64
 7   Embarked     1307 non-null   object 
 8   Survived     1309 non-null   int64  
dtypes: float64(2), int64(5), object(2)
memory usage: 92.2+ KB


In [0]:
#Dropping the row that has NaN values
dataset=dataset.dropna()

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1043 entries, 0 to 1306
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  1043 non-null   int64  
 1   Pclass       1043 non-null   int64  
 2   Sex          1043 non-null   object 
 3   Age          1043 non-null   float64
 4   SibSp        1043 non-null   int64  
 5   Parch        1043 non-null   int64  
 6   Fare         1043 non-null   float64
 7   Embarked     1043 non-null   object 
 8   Survived     1043 non-null   int64  
dtypes: float64(2), int64(5), object(2)
memory usage: 81.5+ KB


In [0]:
#Creating dummy variables
dummies = []
cols = ['Pclass', 'Sex', 'Embarked']
for col in cols:
    dummies.append(pd.get_dummies(dataset[col]))

In [0]:
titanic_dummies = pd.concat(dummies, axis=1)

In [10]:
dataset.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Survived
0            1       3    male  22.0      1      0   7.2500        S         0
1            2       1  female  38.0      1      0  71.2833        C         1
2            3       3  female  26.0      0      0   7.9250        S         1
3            4       1  female  35.0      1      0  53.1000        S         1
4            5       3    male  35.0      0      0   8.0500        S         0

In [0]:
dataset = pd.concat((dataset,titanic_dummies), axis=1)

In [0]:
dataset = dataset.drop(['Pclass', 'Sex', 'Embarked'], axis=1)

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1043 entries, 0 to 1306
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  1043 non-null   int64  
 1   Age          1043 non-null   float64
 2   SibSp        1043 non-null   int64  
 3   Parch        1043 non-null   int64  
 4   Fare         1043 non-null   float64
 5   Survived     1043 non-null   int64  
 6   1            1043 non-null   uint8  
 7   2            1043 non-null   uint8  
 8   3            1043 non-null   uint8  
 9   female       1043 non-null   uint8  
 10  male         1043 non-null   uint8  
 11  C            1043 non-null   uint8  
 12  Q            1043 non-null   uint8  
 13  S            1043 non-null   uint8  
dtypes: float64(2), int64(4), uint8(8)
memory usage: 65.2 KB


In [0]:
#Missing values in Age
dataset['Age']=dataset['Age'].interpolate()

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1043 entries, 0 to 1306
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  1043 non-null   int64  
 1   Age          1043 non-null   float64
 2   SibSp        1043 non-null   int64  
 3   Parch        1043 non-null   int64  
 4   Fare         1043 non-null   float64
 5   Survived     1043 non-null   int64  
 6   1            1043 non-null   uint8  
 7   2            1043 non-null   uint8  
 8   3            1043 non-null   uint8  
 9   female       1043 non-null   uint8  
 10  male         1043 non-null   uint8  
 11  C            1043 non-null   uint8  
 12  Q            1043 non-null   uint8  
 13  S            1043 non-null   uint8  
dtypes: float64(2), int64(4), uint8(8)
memory usage: 65.2 KB


In [0]:
#Loading data to X and y
X = dataset.values
y = dataset['Survived'].values

In [17]:
print(y)

[0 1 1 ... 1 1 0]


In [0]:
#Dropping 'Survived' from X
X = np.delete(X, 8, axis=1)

In [0]:
#Splitting Data to training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [20]:
#Applying Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
#Predicting test results
y_pred=classifier.predict(X_test)

In [22]:
#Confusion Matrix and Accuracy
from sklearn.metrics import confusion_matrix
from sklearn import metrics
cm=confusion_matrix(y_test,y_pred)

print(cm)
print("Accuracy=",metrics.accuracy_score(y_test, y_pred))

[[180   0]
 [  0 133]]
Accuracy= 1.0


In [64]:
#Applying K Nearest Neighbors 
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,metric='manhattan',p=4)
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='manhattan',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=4,
                     weights='uniform')

In [0]:
y_pred=knn.predict(X_test)

In [66]:
cm=confusion_matrix(y_test,y_pred)
print(cm)
print("Accuracy=",metrics.accuracy_score(y_test, y_pred))

[[153  27]
 [ 75  58]]
Accuracy= 0.6741214057507987
